version: "3.8"

services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: glaciar-api
    ports:
      - "5205:8080"
    environment:
      # O .NET vai ler a string de conexão do Supabase daqui em tempo de execução
      - ConnectionStrings__DefaultConnection=${SUPABASE_CONNECTION}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: glaciar-frontend
    ports:
      - "5500:80"
    depends_on:
      - api
    restart: unless-stopped